name: Build Marauder Arduino Bins

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Add Espressif board manager URL
        run: arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install ESP32 Arduino core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install all required libraries
        run: |
          arduino-cli lib install \
            "LinkedList" \
            "ESPAsyncWebServer" \
            "AsyncTCP" \
            "Adafruit NeoPixel" \
            "ArduinoJson" \
            "Adafruit GFX Library" \
            "Adafruit ILI9341" \
            "Adafruit SH110X" \
            "Adafruit STMPE610" \
            "Adafruit TSC2007" \
            "Adafruit TouchScreen" \
            "Adafruit MAX1704X" \
            "MicroNMEA" \
            "espsoftwareserial"

    - name: Debug: Search for invalid FQBN
       run: grep -r 'esp32:esp32-s3' .


      - name: Compile & export binaries
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32s3 \
            --build-path build \
            --export-binaries esp32_marauder/esp32_marauder.ino

      - name: Upload .bin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marauder-arduino-bins
          path: |
            build/bootloader.bin
            build/partition-table.bin
            build/esp32_marauder.ino.bin
