name: Build ESP32 Marauder

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install Required Libraries
        run: |
          arduino-cli lib install "LovyanGFX"
          arduino-cli lib install "LinkedList"
          arduino-cli lib install "ESPAsyncWebServer"
          arduino-cli lib install "AsyncTCP"
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "Adafruit NeoPixel"
          arduino-cli lib install "Adafruit BusIO"
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit MAX1704X"
          arduino-cli lib install "MicroNMEA"
          arduino-cli lib install "EspSoftwareSerial"

      - name: Compile Sketch
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32s3 \
            --build-path build \
            --export-binaries \
            esp32_marauder/esp32_marauder.ino

      - name: Upload Binaries
        uses: actions/upload-artifact@v3.1.2
        with:
          name: firmware-bin
          path: build/*.bin
